version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: lab5_nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./www:/var/www/html
    depends_on:
      - php

  php:
    build: .        
    container_name: lab5_php
    volumes:
      - ./www:/var/www/html
    expose:
      - "9000"
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: lab5_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: lab5_db
      MYSQL_USER: lab5_user
      MYSQL_PASSWORD: lab5_pass
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

  adminer:
    image: adminer
    container_name: lab5_adminer
    restart: always
    ports:
      - "8081:8080"
    depends_on:
      - db

volumes:
  db_data:
